// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.OrderProcessingService.Repositories;

namespace OrderProcessingService.Repositories.Migrations
{
    [DbContext(typeof(EventStoreDBContext))]
    [Migration("20190915064702_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Store.OrderProcessingService.Repositories.OrderAggregate", b =>
                {
                    b.Property<string>("OrderNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentVersion");

                    b.HasKey("OrderNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Store.OrderProcessingService.Repositories.OrderEvent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EventData");

                    b.Property<string>("EventType");

                    b.Property<string>("OrderNumber");

                    b.Property<DateTime>("Timestamp");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Store.OrderProcessingService.Repositories.OrderEvent", b =>
                {
                    b.HasOne("Store.OrderProcessingService.Repositories.OrderAggregate", "Order")
                        .WithMany("Events")
                        .HasForeignKey("OrderNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
