// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.ShippingService;

namespace ShippingService.Migrations
{
    [DbContext(typeof(StoreDBContext))]
    [Migration("20190919111141_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Store.ShippingService.Order", b =>
                {
                    b.Property<string>("OrderNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Shipped");

                    b.Property<string>("ShippingAddress");

                    b.HasKey("OrderNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Store.ShippingService.OrderedProduct", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrderNumber");

                    b.Property<string>("ProductNumber");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Store.ShippingService.ShippingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("LastSeqNr");

                    b.HasKey("Id");

                    b.ToTable("ShippingInfo");
                });

            modelBuilder.Entity("Store.ShippingService.OrderedProduct", b =>
                {
                    b.HasOne("Store.ShippingService.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
